# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:00
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20171030_0047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.RenameModel(
            old_name='Movie_List',
            new_name='MovieList',
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='movielist',
            options={'verbose_name': 'Movie List', 'verbose_name_plural': 'Movie List'},
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='hi', editable=False, populate_from='name', unique_with=['id']),
            preserve_default=False,
        ),
    ]
