# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 07:10
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20171101_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastAndCrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('birthday', models.DateField(default='2017-08-11')),
                ('api_id', models.IntegerField()),
                ('biography', models.TextField(default='Biography yet to added', verbose_name='Biography')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image')),
                ('popularity', models.IntegerField(default=1)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique_with=['id'])),
                ('homepage', models.URLField(blank=True, null=True, verbose_name='Homepage')),
            ],
            options={
                'verbose_name_plural': 'Cast And Crew',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200, verbose_name='Role')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.CastAndCrew')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Movie')),
            ],
            options={
                'verbose_name_plural': 'Role',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, through='review.Role', to='review.CastAndCrew'),
        ),
    ]
