# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 07:44
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20171102_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castandcrew',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique_with=['api_id']),
        ),
    ]
