# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20171102_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castandcrew',
            name='birthday',
        ),
    ]
