# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_remove_castandcrew_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castandcrew',
            name='homepage',
        ),
    ]
