# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_remove_castandcrew_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_crew', to='review.CastAndCrew'),
        ),
    ]
