# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_auto_20171128_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=3),
        ),
    ]
