# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_movie_imdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='castandcrew',
            name='image_thumbnail',
            field=models.URLField(blank=True, null=True, verbose_name='Image_thumbnail'),
        ),
    ]
