# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:09
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Movie_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('api_id', models.IntegerField()),
                ('collected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('synopsis', models.TextField(default='Synopsis yet to added', verbose_name='Synopsis')),
                ('rel_date', models.DateField(default='2017-08-11')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique_with=['title'])),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('genre', models.ManyToManyField(blank=True, to='review.Genre')),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
