# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='popularity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='movies',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='movies',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
